### ISSUE TITLE
Default theme with color scheme causes missing contrast in autocomplete box

### ISSUE THREAD

**Issue by svictoreq** [Monokai/monokai-pro-sublime-text#46] opened 2017-10-16 22:36 UTC
When using the default Sublime theme with any of the schemes, the contrast in the autocomplete box is missing:
![image](https://user-images.githubusercontent.com/29575744/31638123-f113781a-b29f-11e7-8625-2e15a0045ed7.png)

The current Sublime Text version I'm using is the Build 3149, but it also happens in the Stable Build 3143.

**Comment by TheIronBorn** [comment] 2017-12-22 21:14
Duplicate of #16 (unless the issue is new to the Default theme)

**Comment by Monokai** [comment] 2017-12-29 10:41
Monokai Pro is designed to work as a whole. So color scheme and theme in one. I think @TheIronBorn is right that it's the same issue as #16

**Closed by Monokai** 2017-12-29 10:41 UTC
